// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

component MyLayout inherits VerticalLayout {
    padding: 5px;
    Rectangle {
        padding: 5px;
    }
}

component MyLayout2 inherits VerticalLayout {
    padding-top: 5px;
}

component MyLayoutDerived inherits MyLayout2 { }

export component MyDialog inherits Dialog {
    padding: 5px;
    Rectangle {
        padding: 5px;
    }
}

export component Test {

    padding: 8px;

    padding-bottom: 2px;

    Rectangle {
        padding-top: 2px;
        GridLayout {
            padding: 5px;
        }
    }

    HorizontalLayout {
        padding-left: 5px;
        Rectangle {
            padding: 5px;
            Rectangle {
                padding: 5px;
            }
        }
    }

    MyLayout {
        padding-left: 10px;
        Rectangle {
            padding: -5px;
        }
    }

    if false: MyDialog {
        padding-left: 10px;
    }

    MyLayout2 {
        padding-right: 10px;
    }

    MyLayout2 {
        padding-top: 10px;
    }

    MyLayoutDerived {
        padding-right: 10px;
    }

    MyLayoutDerived {
        padding-top: 10px;
    }
}
